---
user:
  name: alulord
  shell: /usr/bin/zsh
  uid: 1000
  group: users
  log:
    dir: .log
    rotate: 8
  timezone: Europe/Bratislava

dotfiles:
  url: git@github.com:alulord/arch-dotfiles.git
  name: .dotfiles.git

bootloader:
  path: /boot
  theme_path: refind-theme-regular
  kernel_parameters:  "initrd=amd-ucode.img libahci.ignore_sss=1 quiet splash loglevel=3 rd.udev.log_priority=3 vt.global_cursor_default=0"

pacman:
  base_packages:
    - alacritty
    - gptfdisk
    - man-db
    - man-pages
    - nano
    - openssh
    - pkgfile
    - python-pip
    - wget
    - zsh
    - gnome-keyring
  additional_packages:
    - atom
    - filezilla
    - firefox
    - gimp
    - gsimplecal
    - htop
    - keepassxc
    - nemo
    - nemo-fileroller
    - nemo-terminal
    - neofetch
    - rsync
    - transmission-gtk
    - steam
    - pacman-contrib
    - coreutils
    - moreutils
    - dateutils
    - jq
    - screen
    - fwupd
    - phototonic
    - papirus-icon-theme
    - lm_sensors
    - seahorse
    - network-manager-applet

aur:
  packages:
    - ctop
#    - libpdfium-nojs
#    - megasync
#    - nemo-megasync
#    - spotify
    - teamviewer
    - gnome-screenshot
    - yay

multimedia:
  packages:
    - playerctl
    - a52dec
    - libmad
    - libmpeg2
    - lxappearance
    - ffmpegthumbnailer

fonts:
  packages:
    - terminus-font
    - gucharmap
    - ttf-jetbrains-mono
  aur_packages:
    - nerd-fonts-inconsolata-go
    - ttf-font-awesome-4
#    - freetype2-cleartype

filesystem:
  packages:
    - ntfs-3g
    - btrfs-progs
    - snapper
    - snap-pac

video_drivers:
  - nouveau
  - amdgpu

display_manager:
notebook:
desktop_environment: sway

gdm:
  sound: False
  font_scaling_factor: 1
  logo_path: False
  touchpad:
    tap_to_click: True
  accessibility_menu: True

x:
  middle_click_button: "274"
  keyboard_model: "pc105"

network:
  dispatcher: True
  wireless_packages:
    - wireless_tools
    - iw
    - iwd

gnupg:
  enable_agent: True
  emulate_ssh: True

hostsctl:
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

bluetooth:
  disable: False

journal:
  max_size: 500M
luks_uuid: 5a93d128-8028-4c0a-a74e-a0fa403b68eb
root_uuid: 689d728e-0449-475c-8ffe-1afb7569e3e3
