---
- name: Install redshift
  pacman: name=redshift state=present

- name: Enable redshift-gtk
  become: yes
  become_user: "{{ user.name }}"
  systemd:
    name=redshift-gtk.service
    scope: user
    enabled: yes
    state: started

- name: Allow RedShift to access geoclue
  blockinfile:
    dest: /etc/geoclue/geoclue.conf
    block: |
      [redshift]
      allowed=true
      system=false
      users=