---
- hosts: localhost
  become: yes
#  tasks:
#    - debug: var=ansible_facts
  roles:
    - { role: base, tags: ['base'] }
    - { role: packages, tags: ['packages'] }
    - { role: amd-microcode, tags: ['amd-microcode'], when: "'AuthenticAMD' in ansible_processor" }
    - { role: bootloader, tags: ['bootloader'] }
    - { role: linux, tags: ['linux'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: systemd, tags: ['systemd'] }
    - { role: wireless, tags: ['wireless'], when: "install_wireless|bool == True" }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: reflector, tags: ['reflector'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: hostsctl, tags: ['hostsctl'] }
    - { role: x, tags: ['x'] }
    - { role: cron, tags: ['cron'] }
    - { role: laptop, tags: ['laptop'], when: "is_laptop|bool == True" }
    - { role: ssh, tags: ['ssh'] }
    - { role: multimedia, tags: ['multimedia'] }
    - { role: lightdm, tags: ['lightdm'] }
    - { role: sound, tags: ['sound'] }
    - { role: bluetooth, tags: ['bluetooth'], when: "install_bluetooth|bool == True" }
    - { role: i3, tags: ['i3'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: docker, tags: ['docker'] }
    - { role: packages, tags: ['packages'] }
    - { role: archive, tags: ['archive'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: vpn, tags: ['vpn'] }
    - { role: clipboard, tags: ['clipboard'] }
    - { role: virtualbox, tags: ['virtualbox'] }

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      default: test
#      confirm: yes
    - name: hostname
      prompt: "Enter desired hostname"
      default: aluwork
      private: no
    - name: ssh_src
      prompt: "Enter location with ssh keys"
      default: /install/.ssh
      private: no
    - name: is_laptop
      prompt: "Should we install laptop features?"
      default: true
      private: no
    - name: install_bluetooth
      prompt: "Does the device has bluetooth?"
      default: true
      private: no
    - name: install_wireless
      prompt: "Does the device has WiFi?"
      default: true
      private: no
