---
- hosts: localhost
  become: yes
#  tasks:
#    - debug: var=ansible_facts
  roles:
    - { role: base, tags: ['base'] }
    - { role: packages, tags: ['packages'] }
    - { role: amd-microcode, tags: ['amd-microcode'], when: "'AuthenticAMD' in ansible_processor" }
    - { role: bootloader, tags: ['bootloader'] }
    - { role: linux, tags: ['linux'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: systemd, tags: ['systemd'] }
    - { role: wireless, tags: ['wireless'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: reflector, tags: ['reflector'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: hostsctl, tags: ['hostsctl'] }
    - { role: x, tags: ['x'] }
    - { role: cron, tags: ['cron'] }
    - { role: laptop, tags: ['laptop'] }
    - { role: tlp, tags: ['tlp'] }
    - { role: asus, tags: ['asus'], when: "notebook == 'asus'" }
    - { role: ssh, tags: ['ssh'] }
    - { role: multimedia, tags: ['multimedia'] }
    - { role: video, tags: ['video'] }
    - { role: cups, tags: ['cups'] }
    - { role: dconf, tags: ['dconf'], when: "display_manager == 'gdm'" }
    - { role: gdm, tags: ['gdm'], when: "display_manager == 'gdm'" }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }
    - { role: sound, tags: ['sound'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: i3, tags: ['i3'], when: "desktop_environment == 'i3'" }
    - { role: sway, tags: ['sway'], when: "desktop_environment == 'sway'" }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: docker, tags: ['docker'] }
    - { role: packages, tags: ['packages'] }
    - { role: archive, tags: ['archive'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: vpn, tags: ['vpn'] }
    - { role: clipboard, tags: ['clipboard'] }
    - { role: virtualbox, tags: ['virtualbox'] }

  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      default: test
#      confirm: yes
    - name: hostname
      prompt: "Enter desired hostname"
      default: aluwork
      private: no
    - name: ssh_src
      prompt: "Enter location with ssh keys"
      default: /install/.ssh
      private: no
