---
- name: Install necessary pacman packages
  pacman:
    name: "{{ pacman.additional_packages }}"
    state: present

- name: Import spotify gpg key 1
  command: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

- name: Import spotify gpg key 2
  command: gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45

- name: Install necessary aur packages
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: "{{ aur.packages }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"