---
- name: Clone Oh My ZSH repo for user.
  become: yes
  become_user: "{{ user.name }}"
  aur: name=zplug state=present

- name: Copy zshrc to root
  synchronize:
    dest: /root/
    src: /home/{{ user.name }}/.zshrc
    archive: no

- name: Copy powerlevel to root
  synchronize:
    dest: /root/
    src: /home/{{ user.name }}/.p10k.zsh
    archive: no

