---
- name: Clone Oh My ZSH repo for user.
  become: yes
  become_user: "{{ user.name }}"
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh"
    dest: "/home/{{ user.name }}/.oh-my-zsh"
    depth: 1

- name: Add zsh autosuggestions plugin
  become: yes
  become_user: "{{ user.name }}"
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/home/{{ user.name }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Add zsh fast syntaxt highlighting plugin
  become: yes
  become_user: "{{ user.name }}"
  git:
    repo: "https://github.com/zdharma/fast-syntax-highlighting.git"
    dest: "/home/{{ user.name }}/.oh-my-zsh/custom/plugins/fast-syntax-highlighting"
    depth: 1

- name: Add powerlevel10k zsh theme
  become: yes
  become_user: "{{ user.name }}"
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "/home/{{ user.name }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Link zsh aliases plugin
  become: yes
  become_user: "{{ user.name }}"
  file:
    src: /home/{{ user.name }}/.local/share/scripts/aliases
    path: /home/{{ user.name }}/.oh-my-zsh/custom/plugins/aliases
    state: link

- name: Copy oh-my-zsh to root
  synchronize:
    dest: /root/
    src: /home/{{ user.name }}/.oh-my-zsh

- name: Copy zshrc to root
  synchronize:
    dest: /root/
    src: /home/{{ user.name }}/.zshrc

- name: Copy powerlevel to root
  synchronize:
    dest: /root/
    src: /home/{{ user.name }}/.p10k.zsh


- name: Copy aliases to root
  synchronize:
    dest: /root/.oh-my-zsh/custom/plugins/
    src: /home/{{ user.name }}/.local/share/scripts/aliases

- name: Remove ssh-keygen from root zshrc
  lineinfile:
    path: /root/.zshrc
    state: absent
    regexp: 'ssh-keygen'