---
- name: Create .ssh dir
  file:
    path: /home/{{ user.name }}/.ssh
    mode: 700
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory


- name: Copy ssh keys
  copy:
    dest: "/home/{{ user.name }}"
    src: "{{ ssh_src }}"


- name: Set .ssh permissions for owner
  file:
    path: /home/{{ user.name }}/.ssh
    mode: u+rw
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    recurse: yes


- name: Set .ssh permissions for .ssh dir
  file:
    path: /home/{{ user.name }}/.ssh
    mode: +x
    owner: "{{ user.name }}"
    group: "{{ user.group }}"


- name: Remove .ssh permissions for group and others
  file:
    path: /home/{{ user.name }}/.ssh
    mode: go-rwx
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    recurse: yes

- name: Install keychain
  pacman: name=keychain state=present

- name: Install x11-ask-pass
  pacman: name=x11-ssh-askpass state=present

- name: Export SSH_ASKPASS environment variable
  lineinfile: dest=/etc/profile
              state=present
              line="export SSH_ASKPASS=\"/usr/lib/ssh/x11-ssh-askpass\""
