---
- name: Install i3 packages
  pacman:
    name:
      - picom
      - dmenu
      - dunst
      - perl-anyevent-i3
      - gnome-screenshot
      - python-pywal
    state: present

- name: Install i3 aur packages
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - betterlockscreen
      - i3-gaps-rounded-git
      - i3-volume
      - autotiling
      - rofi-git
      - polybar
      - xidlehook
      - python-fontawesome
      - todotxt
      - i3exit
    state: present

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF

- name: Create directory for betterlockscreen drop-in service
  file: path=/etc/systemd/system/betterlockscreen@{{ user.name }}.d state=directory

- name: Override betterlockscreen service
  template:
    src: "betterlockscreen@.service"
    dest: "/etc/systemd/system/betterlockscreen@{{ user.name }}.d/override-locker.conf"
  notify:
    - reload systemd config

- name: Enable betterlockscreen sleep hook
  systemd:
    name: "betterlockscreen@{{ user.name }}.service"
    enabled: yes