---
- name: Install TLP
  pacman:
    name:
      - x86_energy_perf_policy
      - ethtool
      - smartmontools
      - tlp
    state: present

- name: Push TLP btrfs config
  copy:
    src: tlp/20-btrfs.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp

- name: Push TLP battery threshold config
  copy:
    src: tlp/20-battery.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - laptop

- name: Install TLP radio device config
  pacman: name=tlp-rdw state=present
  notify:
    - restart tlp
  tags:
    - wireless

- name: Push TLP radio device config
  copy:
    src: tlp/20-rdw.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - wireless

- name: Push TLP PCIe config
  copy:
    src: tlp/20-pcie.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - tlp

- name: Mask systemd radio service
  command: systemctl mask systemd-rfkill.service
  tags:
    - wireless

- name: Mask systemd radio socket
  command: systemctl mask systemd-rfkill.socket
  tags:
    - wireless

- name: Enable TLP
  service:
    name: tlp.service
    enabled: yes
