---
- name: Install sway packages
  pacman:
    name:
      - rofi
      - dmenu
      - swayidle
      - waybar
      - wl-clipboard
      - sway
      - xorg-server-xwayland
      - brightnessctl
      - mako
      - grim
      - slurp
      - qt5-wayland
      - gammastep
      - xsettingsd
    state: present

- name: Install sway aur packages
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - swaylock-effects-git
      - sway-alttab-bin
#      - j4-dmenu-desktop
    state: present

- name: Install brightness controll for laptop
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: wlr-brightness-git
  tags:
    - laptop

- name: Create dropin directory for getty service
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: Template getty service
  template:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    src: getty

- name: Template sway service
  template:
    dest: /etc/systemd/system/sway@.service
    src: sway@.service

- name: Template sway service
  template:
    dest: /etc/systemd/system/sway-debug@.service
    src: sway-debug@.service

- name: Install i3ipc for autorename workspaces script
  become: yes
  become_user: "{{ user.name }}"
  pip:
    name: i3ipc
    extra_args: --user

- name: Enable sway service
  systemd:
    name: sway@1.service
    enabled: no

- name: Install psutil for dconf
  become: yes
  become_user: "{{ user.name }}"
  pip:
    name: psutil
    extra_args: --user

- name: Setup GNOME theme
  become: yes
  become_user: "{{ user.name }}"
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "'Arc-Dark'"

- name: Setup GNOME icon theme
  become: yes
  become_user: "{{ user.name }}"
  dconf:
    key: /org/gnome/desktop/interface/icon-theme
    value: "'Green-Maia'"

- name: Setup GNOME cursor theme
  become: yes
  become_user: "{{ user.name }}"
  dconf:
    key: /org/gnome/desktop/interface/cursor-theme
    value: "'Volantes-Cursors'"

- name: Check geoclue config file exists.
  stat:
    path: /etc/geoclue/geoclue.conf
  register: g

- name: Add gammastep to geoclue config
  blockinfile:
    path: /etc/geoclue/geoclue.conf
    block: |
      [gammastep]
      allowed=true
      system=false
      users=
  when: g.stat.exists
