---
- name: Install syncthing
  pacman: 
    name: 
      - syncthing
      - syncthing-gtk
    state: present

- name: Copy syncthing service to user dir
  copy:
    src: /lib/systemd/user/syncthing.service
    dest: "/home/{{ user.name }}/.config/systemd/user/"

- name: Start syncthing service as user
  become: yes
  become_user: "{{ user.name }}"
  systemd:
    user: yes
    name: syncthing.service
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
